---
title:  |
        | \vspace{-3cm} Pergunta 2
geometry: margin=2cm
fig_width: 7 
fig_height: 6 
output:
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.width=7, fig.height=3.5) 
```




```{r}
pacman::p_load(rio, ggplot2, dplyr, ggthemes)

time_use <- import("./TIME_USE_24092022.csv")

time_use <- subset(time_use, País != "África do Sul")
man_time_use <- subset(time_use, Sexo =="Homens")
man1_time_use <- subset(man_time_use, Ocupação == "Outros")
man2_time_use <- subset(man_time_use, Ocupação == "Trabalho remunerado ou estudo")

rownames(man1_time_use) <- seq(length=nrow(man1_time_use))
rownames(man2_time_use) <- seq(length=nrow(man2_time_use))

other <- subset(man1_time_use, select = -c(Ocupação, Sexo))
paid_work_study <- subset(man2_time_use, select = -c(Ocupação, Sexo))

data <- data.frame(
  group = c(rep("Outros", nrow(other)), rep("Trabalho Remunerado ou Estudo", nrow(paid_work_study))),
  value = c(other[,2], paid_work_study[,2])
)

ggplot(data, aes(x=value, y=group, fill=group)) +
  geom_boxplot() +
  scale_fill_manual(values = c("#f44747", "#5cadeb")) +
  geom_jitter(color="#716c6c", size=1.7, alpha=0.9) +
  labs(title = "Tempo de Atividades Diárias",
       subtitle = "Tempo médio diário em horas (Homens)") +
     labs(fill = "Grupos") +
     theme(legend.position = "none") +
     xlab("Tempo médio diário (horas)") +
     ylab("")

```


